"""remove_ghost_contract

Revision ID: 0a4312659782
Revises: 47519c0bf986
Create Date: 2025-04-08 15:33:05.159432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a4312659782"
down_revision: Union[str, None] = "47519c0bf986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "ghost_contract_address")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "ghost_contract_address",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
