"""tx_receipt

Revision ID: 22319ddb113d
Revises: 99015c5b5b78
Create Date: 2025-05-28 19:06:34.835960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22319ddb113d"
down_revision: Union[str, None] = "99015c5b5b78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("num_of_initial_validators", sa.Integer(), nullable=True),
    )
    op.add_column(
        "transactions", sa.Column("last_vote_timestamp", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("rotation_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "rotation_count")
    op.drop_column("transactions", "last_vote_timestamp")
    op.drop_column("transactions", "num_of_initial_validators")
    # ### end Alembic commands ###
