"""config_appeal_rounds

Revision ID: 224600873d38
Revises: 2a4ac5eb9455
Create Date: 2025-02-03 10:04:57.725510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "224600873d38"
down_revision: Union[str, None] = "2a4ac5eb9455"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("config_appeal_rounds", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("appeal_round", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "appeal_round")
    op.drop_column("transactions", "config_appeal_rounds")
    # ### end Alembic commands ###
