"""validators_private_key

Revision ID: 47519c0bf986
Revises: 130836786511
Create Date: 2025-03-11 18:18:33.157960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47519c0bf986"
down_revision: Union[str, None] = "130836786511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "validators", sa.Column("private_key", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validators", "private_key")
    # ### end Alembic commands ###
