"""was_accepted

Revision ID: b80e321b5846
Revises: a4a32d27dde2
Create Date: 2025-01-03 15:33:21.338157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b80e321b5846"
down_revision: Union[str, None] = "a4a32d27dde2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("was_accepted", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "was_accepted")
    # ### end Alembic commands ###
