"""queued_transactions

Revision ID: ba7e1d24cc0e
Revises: a4a32d27dde2
Create Date: 2025-01-09 13:48:43.456221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba7e1d24cc0e"
down_revision: Union[str, None] = "a4a32d27dde2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("queued", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "queued")
    # ### end Alembic commands ###
