FROM fabiocicerchia/nginx-lua:1.27.2-almalinux9.4-20240923
# Install lua-cjson
RUN luarocks install lua-cjson
# Configure nginx for reverse proxy
RUN echo 'server { \
    listen 80; \
    location / { \
        proxy_pass http://host.docker.internal:8000; \
        proxy_set_header Host $host; \
        proxy_set_header X-Real-IP $remote_addr; \
    } \
}' > /etc/nginx/conf.d/default.conf
EXPOSE 80