FROM fabiocicerchia/nginx-lua:1.27.2-almalinux9.4-20240923

RUN luarocks install lua-cjson

RUN echo 'server { \
    listen 80; \
    access_log /dev/stdout combined buffer=512k flush=1s; \
    error_log /dev/stderr debug; \
    location / { \
        proxy_pass http://mock-server:8000; \
        proxy_set_header Host \$host; \
        proxy_set_header X-Real-IP \$remote_addr; \
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; \
        proxy_set_header X-Forwarded-Proto \$scheme; \
        add_header X-Debug-Message "Request proxied to mock-server" always; \
        access_log /dev/stdout combined buffer=512k flush=1s; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80